backend:
  name: git-gateway

media_folder: "static/data"
public_folder: "data"

collections:
  - name: "spurt_og_svarad"
    editor:
      preview: false
    label: "Spurt & Svarað"
    folder: "static/content/spurt_og_svarad"
    create: true
    fields:
      - { label: "Titill", name: "title", widget: "string" }
      - { label: "Mynd", name: "mynd", widget: "image" }
      - { label: "Texti", name: "body", widget: "markdown" }
      - {
          label: "Dagsetning",
          name: "dagsetning",
          widget: "datetime",
          format: "YYYY-MM-DD",
          hint: "Óþarfi að breyta þessum dálk - Nema þú viljir endurraða færslum.",
        }
  - name: "frettir"
    editor:
      preview: false
    label: "Fréttir"
    folder: "static/content/frettir"
    create: true
    fields:
      - { label: "Titill", name: "title", widget: "string" }
      - {
          label: "Dagsetning fréttar",
          name: "dagsetning",
          widget: "datetime",
          format: "YYYY-MM-DD",
        }
      - { label: "Texti", name: "body", widget: "markdown" }
  - name: "verkefnastofa_borgarlinu"
    editor:
      preview: false
    label: "Verkefnastofa Borgarlínu"
    folder: "static/content/verkefnastofa_borgarlinu"
    create: true
    fields:
      - { label: "Titill", name: "title", widget: "string" }
      - { label: "Texti", name: "body", widget: "markdown" }
  - name: "hopar"
    editor:
      preview: false
    label: "Hópar"
    folder: "static/content/hopar"
    create: true
    fields:
      - { label: "Nafn", name: "title", widget: "string" }
      - { label: "Texti", name: "texti", widget: "text" }
  - name: "starfsfolk"
    editor:
      preview: false
    label: "Starfsfólk"
    folder: "static/content/starfsfolk"
    create: true
    fields:
      - { label: "Nafn", name: "title", widget: "string" }
      - { label: "Mynd", name: "portrait_mynd", widget: "image" }
      - { label: "Starfslýsing", name: "starfslysing", widget: "string" }
      - { label: "Netfang", name: "netfang", widget: "string" }
      - {
          label: "Verkefnastjóri",
          name: "verkefnastjori",
          widget: "boolean",
          hint: "Hakaðu við þetta ef einstaklingur er verkefnastjóri",
        }
  - name: "skyrslur"
    editor:
      preview: false
    label: "Skýrslur"
    folder: "static/content/skyrslur"
    create: true
    fields:
      - { label: "Titill", name: "title", widget: "string" }
      - { label: "Texti", name: "body", widget: "markdown", required: false }
      - {
          label: "Viðhengi(pdf)",
          name: "vidhengi-pdf",
          widget: "file",
          required: false,
          hint: "Settu inn *.pdf skrá",
        }
